name: 'Jira release'
description: ' Create Release and Update Issues fix version in Jira'
author: 'Valera Korovelkov'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
inputs:
  release-webhook-url:
    description: 'Url to create release'
    required: true
  issues-webhook-url:
    description: 'Url to update issues'
    required: true
  project-name:
    description: 'Project name'
    required: true
  issue-tag:
    description: 'Issue tag'
    required: true

runs:
  using: node20
  main: dist/index.js
